### ISSUE TITLE
Not saving on Linux Mint 18

### ISSUE THREAD

**Issue by astfarias** [rhcarvalho/byzanz-gui#1]
Set duration, select area and Notifications works, but the file is not created

**Comment by astfarias** [comment]
Ah, just need edit the file and change the directory in 

# Standard screencast folder

FOLDER="$HOME/[YOUR FOLDER]"
If language of SO changed the default

**Comment by rhcarvalho** [comment]
@astfarias thank you for the report. Sorry I did not see this earlier because I was not receiving notifications for this repository.
I've updated the script to support systems using languages other than English, it will now default to the localized pictures folder.
