### ISSUE TITLE
Bad default settings

### ISSUE THREAD

**Issue by ghost** [rhcarvalho/byzanz-gui#5]
One problem with it is,We can't estimate how long our recording takes,
option to select area of screen would be better,

I have decided to record for 3 seconds, I got a notification which says, recording starts within 10 seconds.

I don't known when it is exactly starting and I get a notification saying gif is saved.
It would be better, if we get notified when screen-recording starts

**Comment by rhcarvalho** [comment]
@Looserof7 you are right. One difficulty with notification when the recording starts is that the notification itself may end up in the recorded GIF.

More sophisticated software like [Shutter](http://shutter-project.org/) can show countdown notifications that are not captured in screenshots (though it can't produce animated GIFs AFAIK).

While it may be doable, I don't have time to invest on fixing this issue.

**Comment by rhcarvalho** [comment]
> option to select area of screen would be better,

This has been addressed in #6.

For alternative GIF recording software that may be more clever and provide better notifications, please see a [list of alternative software for recording GIFs that promise more features](https://github.com/rhcarvalho/byzanz-gui/blob/b08ea8ef78b63892a4ecfe5da524b2d13e58d9ee/README.md#see-also) in the README.
